class AppURLs:
  authClients = "authClients.json"
  accounts = "accounts.json"
  clients = "clients.json"
  statements = "statements.json"
  authAdmin = "authAdmin.json"
  deleteSolicitations = "deleteAccountSolicitation.json"
  balanceSavingsMonthsxAccount = "balanceSavingsMonthsxAccounts.json"
  balanceSavingsbyId = "balanceSavingsById.json"
  datesToDiscountXtaxByAccount = "datesToDiscountCurrentAccounts.json"
  specialCheck = "specialChecks.json"